# k8s-tools: pin or customize versions for your whole k8s toolchain in one place.
#   Docs: https://github.com/elo-enterprises/k8s-tools
#   Latest: https://github.com/elo-enterprises/k8s-tools/tree/master/docker-compose.yml
services:

  base: &base
    image: k8s:base
    build:
      context: .
      dockerfile_inline: |
        FROM alpine/k8s:1.30.0
        RUN apk --no-cache add procps make
        RUN apk add yq --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community
    network_mode: host
    working_dir: /workspace
    volumes:
      # NB: something like this if you're working with EKS and need AWS creds
      # - ${HOME}/.aws:/root/.aws
      # NB: something like this if you only want to share one file.
      # - "${KUBECONFIG}:/kubeconfig.conf:ro"
      # NB: `.cache` and `.config` as below are used by helm, maybe others?
      - ${PWD}:/workspace
      - ${HOME}/.kube:/root/.kube
      # used by helm, maybe others
      - ${HOME}/.cache:/root/.cache
      - ${HOME}/.config/helm:/root/.config/helm
      - ${HOME}/.local:/root/.local:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      KUBECONFIG: "${KUBECONFIG}"

  helm:
    <<: *base
    entrypoint: helm

  kubectl:
    <<: *base
    entrypoint: kubectl

  # https://github.com/kubernetes-sigs/kustomize
  kustomize:
    <<: *base
    entrypoint: kustomize

  # https://github.com/databus23/helm-diff
  helm-diff:
    <<: *base
    entrypoint: helm-diff

  # https://github.com/helm-unittest/helm-unittest
  helm-unittest:
    <<: *base
    entrypoint: helm-unittest

  # https://github.com/chartmuseum/helm-push
  helm-push:
    <<: *base
    entrypoint: helm-push

  # https://github.com/kubernetes-sigs/aws-iam-authenticator
  aws-iam-authenticator:
    <<: *base
    entrypoint: aws-iam-authenticator

  # https://github.com/weaveworks/eksctl
  eksctl:
    <<: *base
    entrypoint: eksctl

  # https://github.com/aws/aws-cli
  awscli: # v1
    <<: *base
    entrypoint: awscli

  # https://github.com/bitnami-labs/sealed-secrets
  kubeseal:
    <<: *base
    entrypoint: kubeseal

  # https://github.com/kubernetes-sigs/krew
  krew:
    <<: *base
    entrypoint: krew

  # https://github.com/helmfile/vals
  vals:
    <<: *base
    entrypoint: vals

  # https://github.com/yannh/kubeconform
  kubeconform:
    <<: *base
    entrypoint: kubeconform

  # https://knative.dev/docs/client/install-kn/
  kn: &knative
    <<: *base
    depends_on: ['base']
    image: k8s:kn
    build:
      context: .
      dockerfile_inline: |
        FROM k8s:base as base
        FROM ghcr.io/knative/func/func as builder
        FROM gcr.io/knative-releases/knative.dev/client/cmd/kn:latest
        COPY --from=builder /ko-app/func /ko-app/func
        COPY --from=base /usr/bin/kubectl /usr/bin/kubectl
        RUN apk --no-cache add bash procps make python3
        RUN cp /ko-app/func /usr/local/bin/kn-func

  # https://github.com/arttor/helmify
  helmify:
    <<: *base
    depends_on: ['base']
    image: k8s:helmify
    build:
      context: .
      dockerfile_inline: |
        FROM debian
        RUN apt-get update && apt-get install -y curl
        RUN cd /tmp && curl -s -Lo helmify.tgz \
            https://github.com/arttor/helmify/releases/download/v0.4.12/helmify_Linux_i386.tar.gz
        RUN cd /tmp && tar -zxvf helmify.tgz && chmod +x helmify && mv helmify /usr/local/bin/
    entrypoint: helmify
    tty: false
    stdin_open: true

  # https://fission.io/docs/installation/
  fission:
    <<: *base
    depends_on: ['base']
    image: k8s:fission
    build:
      context: .
      dockerfile_inline: |
        FROM k8s:base
        RUN curl -s -Lo fission \
            https://github.com/fission/fission/releases/download/v1.20.1/fission-v1.20.1-linux-amd64
        RUN chmod +x fission && mv fission /usr/local/bin/
    entrypoint: fission


  # https://github.com/kubernetes/kompose/blob/main/docs/installation.md#github-release
  kompose:
    <<: *base
    depends_on: ['base']
    image: k8s:kompose
    build:
      context: .
      dockerfile_inline: |
        FROM k8s:base
        RUN curl -L https://github.com/kubernetes/kompose/releases/download/v1.33.0/kompose-linux-amd64 -o /usr/bin/kompose
        RUN chmod ugo+x /usr/bin/kompose
    entrypoint: kompose

  # https://k3d.io/
  k3d:
    <<: *base
    depends_on: ['base']
    image: k8s:k3d
    build:
      context: .
      dockerfile_inline: |
        FROM k8s:base
        RUN curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | TAG=v5.3.0 bash
    entrypoint: k3d

  # https://k9scli.io/
  k9s:
    # NB: no inheritance from `base` since `build` conflicts with `image`.
    build: https://github.com/derailed/k9s.git#master:/
    tty: true
    network_mode: host
    volumes:
      - type: bind
        source: ${KUBECONFIG}
        target: /kubeconfig.conf
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      KUBECONFIG: "/kubeconfig.conf"
    entrypoint: k9s

  yq:
    # NB: included in base, but this option is slimmer
    image: mikefarah/yq:4.43.1

  jq:
    # NB: included in base, but this option is slimmer
    image: ghcr.io/jqlang/jq:1.7.1
