site_name: k8s-tools
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
# markdown_extensions:
#   - markdown_include.include:
#       base_path: .
#   - admonition
nav:
  - overview.md
  - features.md
  - compose.mk.md
  - k8s.mk.md
  - demos
docs_dir: docs
site_dir: site
  