# See also: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Project Tests
on:
  workflow_call: {}
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
      - '**.md.j2'
      - '**.png'
      - '**.gif'
permissions:
  contents: read
jobs:
  test:
    name: Integration/Smoke/E2E Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initialize
        run: make clean init
      - name: Build
        run: make build
      - name: Integration Tests
        run: make integration-test
      - name: Smoke Tests
        run: make smoke-test
      - name: E2E Tests
        run: make e2e-test
