# See also: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Project Tests
on:
  workflow_call: {}
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
      - '**.png'
permissions:
  contents: read
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initialize
        run: make clean init
      - name: Build
        run: make build
      - name: Integration Tests
        run: make itest
      - name: Smoke Tests
        run: make stest
